### ISSUE TITLE
0.9.10 broke our app

### ISSUE THREAD

**Issue by naBausch** [Stanko/react-animate-height#21]
hey @Stanko 

thanks for your plugin - we are using it for a small application and it worked quite well.

Unfortunately updating from 0.9.9 to 0.9.12 (probably already to 0.9.10) broke almost everything:

The height calculation of `height:auto` for flexbox doesn't work for `overflow:hidden; height:0` as the children of flexbox will try to fit inside the flexbox.
It might also be because of the `display: none` changes.

Also we had to change our code from:

```js 
import * as AnimateHeight from 'react-animate-height';
```

to

```js
import AnimateHeight from 'react-animate-height';
```

Could you please introduce [semantic versioning](http://semver.org) for future releases so we and other users of your plugin are able to see in advance that updating might break something?

Thanks in advance :)

**Comment by Stanko** [comment]
Hello @naBausch,
I will into both of your issues and get back to you. It would great if you can provide me with the example that 0.9.10 broke.

Cheers!

**Comment by Stanko** [comment]
@naBausch I can't replicate that behavior and therefore I need code example to be able to fix it.

I'll try to follow semantic versioning from now on.

**Comment by naBausch** [comment]
Hi @Stanko,

sorry for the delay, I tried to create a very [simplified example](https://stackblitz.com/edit/react-djbqvz) for this issue.
The example shows a text, which should open a box via click, but instead the 'animate-height-content' won't be displayed. 
This is caused by the my css classes, which set a display:flex on both AnimateHeight elements.
 
```js 
 <AnimateHeight
        ...
       className={'animate-height'}
       contentClassName={'animate-height-content'}
      >
       ... 
      </AnimateHeight>
```
```css 
   .animate-height,
   .animate-height-content {
      display: -webkit-box;
      display: -ms-flexbox;
      display: flex;
      -webkit-box-orient: vertical;
      -webkit-box-direction: normal;
      -ms-flex-direction: column;
      flex-direction: column;
}
```
Thanks for your help :)
