### ISSUE TITLE
Hi there! Great component. Just curious will there be a slideRIght / slideLeft version ?

### ISSUE THREAD

**Issue by tweetzal** [Stanko/react-animate-height#26]

**Comment by Stanko** [comment]
@tweetzal slide left/right is really easy to achieve using CSS transitions, so I don't plan to add it.

```css
.Component {
  transition: width 500ms;
  width: 100%;
}

.Component--closed {
  width: 0;
}
```

And then just toggle `Component--closed` class.

Cheers!
