### ISSUE TITLE
onAnimationEnd and children

### ISSUE THREAD

**Issue by pryahin** [Stanko/react-animate-height#61]
Hello, I found a strange behavior on the onAnimationEnd event.
If an element has a child that has an animation, the onAnimationEnd event will be triggered after the animation of the child has completed.

I think that onAnimationEnd should only work for AnimateHeight element, and should not be triggered on children's animations.

**Comment by Stanko** [comment]
Hello @pryahin,
I can't replicate what you are describing, check the quick example I made:
https://codesandbox.io/s/241mpxk9x0

Please try to recreate the issue on https://codesandbox.io so I can investigate what is happening.

Cheers!

**Comment by pryahin** [comment]
I meant that if some element has css animation while he is a child AnimateHeight, then after the animation the element will work onAnimationHeight parent

Try adding this code to the style.css
```css
@keyframes open {
  from {
    opacity: 0;
  }
  to {
    opacity: 1
  }
}

h2 {
  opacity: 0;
  animation: open 1s ease-in-out
}
```
